language: scala

addons:
    postgresql: "9.4"

before_script:
    - npm install -g bower
    - bower install
    - psql -c 'create database desafiohu;' -U postgres

script:
    - sbt test
    - sbt stage


jdk:
    - oraclejdk8